# Generated by Django 5.0.6 on 2024-06-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
