# Generated by Django 4.0 on 2024-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_is_admin_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sport',
            field=models.CharField(blank=True, choices=[('arnis', 'Arnis'), ('volleyball', 'Volleyball'), ('table_tennis', 'Table Tennis')], max_length=20, null=True),
        ),
    ]
