# Generated by Django 4.0 on 2024-10-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_customuser_is_admin_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labananmatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
            preserve_default=False,
        ),
    ]
