# Generated by Django 4.0 on 2024-10-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_labananmatch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubletennismatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formmatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singletennismatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volleyballmatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
            preserve_default=False,
        ),
    ]
