from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myapp'

urlpatterns = [    
    path('', views.landing, name='landing'),
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('sports/', views.sports, name='sports'),
    path('arnis/', views.arnis, name='arnis'),
    path('volleyball/', views.volleyball, name='volleyball'),
    path('table_tennis/', views.tennis, name='table_tennis'),
    path('arnis_labanan/', views.arnis_labanan, name='arnis_labanan'),
    path('labanan_display/', views.labanan_display, name='labanan_display'),
    path('labanan_sheet/', views.labanan_sheet, name='labanan_sheet'),
    path('arnis_anyo/', views.arnis_anyo, name='arnis_anyo'),
    path('anyo_display/', views.anyo_display, name='anyo_display'),    
    path('anyo_sheet/', views.anyo_sheet, name='anyo_sheet'),
    path('arnis_sport_data/', views.arnis_school_year, name='arnis_sport_data'),
    path('arnis_sport_details/<int:year_id>/', views.arnis_details, name='arnis_sport_details'),
    path('volleyball_display/', views.volleyball_display, name='volleyball_display'),
    path('volleyball_sport_data/', views.volleyball_school_year, name='volleyball_sport_data'),
    path('volleyball_sport_details/<int:year_id>/', views.volleyball_details, name='volleyball_sport_details'),
    path('add_form_player/<int:year_id>/', views.add_form_player, name='add_form_player'),
    path('add_labanan_player/<int:year_id>/', views.add_labanan_player, name='add_labanan_player'),
    path('edit_form_player/<int:player_id>/', views.edit_form_player, name='edit_form_player'),
    path('edit_labanan_player/<int:player_id>/', views.edit_labanan_player, name='edit_labanan_player'),
    path('add_referee/<int:year_id>/', views.add_referee, name='add_referee'),
    path('edit_referee/<int:referee_id>/', views.edit_referee, name='edit_referee'),
    path('add_judge/<int:year_id>/', views.add_judge, name='add_judge'),
    path('edit_judge/<int:judge_id>/', views.edit_judge, name='edit_judge'),
    path('add_recorder/<int:year_id>/', views.add_recorder, name='add_recorder'),
    path('edit_recorder/<int:recorder_id>/', views.edit_recorder, name='edit_recorder'),
    path('add_tabulator/<int:year_id>/', views.add_tabulator, name='add_tabulator'),
    path('edit_tabulator/<int:tabulator_id>/', views.edit_tabulator, name='edit_tabulator'),
    path('add_timer/<int:year_id>/', views.add_timer, name='add_timer'),
    path('edit_timer/<int:timer_id>/', views.edit_timer, name='edit_timer'),
    path('add_manager/<int:year_id>/', views.add_manager, name='add_manager'),
    path('edit_manager/<int:manager_id>/', views.edit_manager, name='edit_manager'),
    path('add_college/', views.add_college, name='add_college'),
    path('edit_college/<int:college_id>/', views.edit_college, name='edit_college'),
    path('add_year/', views.add_school_year, name='add_year'),
    path('api/anyo_players/', views.players_list, name='players_list'),
    path('api/labanan_players/', views.bracket_list, name='bracket_list'),
    path('api/form_players/', views.bracket_list1, name='bracket_list1'),
    path('arnis_bracket/', views.arnis_bracket, name='arnis_bracket'),
    path('volleyball_scoreboard/', views.volleyball_scoreboard, name='volleyball_scoreboard'),
    path('add_team/<int:year_id>/', views.add_team, name='add_team'),
    path('edit_team/<int:team_id>/', views.edit_team, name='edit_team'),
    path('view_players/<int:team_id>/', views.view_players, name='view_players'),
    path('add_volleyball_player/<int:team_id>/', views.add_volleyball_player, name='add_volleyball_player'),
    path('edit_volleyball_player/<int:player_id>/', views.edit_volleyball_player, name='edit_volleyball_player'),
    path('timer/', views.timer, name='timer'),
    path('volleyball_sheet/', views.volleyball_sheet, name='volleyball_sheet'),
    path('single_tennis_scoreboard/', views.stennis_scoreboard, name='stennis_scoreboard'),
    path('single_tennis_display/', views.stennis_display, name='stennis_display'),
    path('single_tennis_sheet/', views.stennis_sheet, name='stennis_sheet'),
    path('double_tennis_scoreboard/', views.dtennis_scoreboard, name='stennis_scoreboard'),
    path('double_tennis_display/', views.dtennis_display, name='dtennis_display'),
    path('double_tennis_sheet/', views.dtennis_sheet, name='dtennis_sheet'),
    path('add_volleyball_judge/<int:year_id>/', views.add_volleyball_judge, name='add_volleyball_judge'),
    path('edit_volleyball_judge/<int:judge_id>/', views.edit_volleyball_judge, name='edit_volleyball_judge'),
    path('add_volleyball_referee/<int:year_id>/', views.add_volleyball_referee, name='add_volleyball_referee'),
    path('edit_volleyball_referee/<int:referee_id>/', views.edit_volleyball_referee, name='edit_volleyball_referee'),
    path('add_volleyball_scorer/<int:year_id>/', views.add_volleyball_scorer, name='add_volleyball_scorer'),
    path('edit_volleyball_scorer/<int:scorer_id>/', views.edit_volleyball_scorer, name='edit_volleyball_scorer'),
    path('api/volleyball_players/', views.bracket_list2, name='bracket_list2'),
    path('volleyball_bracket/', views.volleyball_bracket, name='volleyball_bracket'),
    path('tennis_sport_data/', views.tennis_school_year, name='tennis_sport_data'),
    path('tennis_sport_details/<int:year_id>/', views.tennis_details, name='tennis_sport_details'),
    path('add_tennis_coach/<int:year_id>/', views.add_tennis_coach, name='add_tennis_coach'),
    path('edit_tennis_coach/<int:coach_id>/', views.edit_tennis_coach, name='edit_tennis_coach'),
    path('add_tennis_umpire/<int:year_id>/', views.add_tennis_umpire, name='add_tennis_umpire'),
    path('edit_tennis_umpire/<int:umpire_id>/', views.edit_tennis_umpire, name='edit_tennis_umpire'),
    path('add_tennis_player/<int:year_id>/', views.add_tennis_player, name='add_tennis_player'),
    path('edit_tennis_player/<int:player_id>/', views.edit_tennis_player, name='edit_tennis_player'),
    path('api/tennis_players/', views.bracket_list3, name='bracket_list3'),
    path('tennis_bracket/', views.tennis_bracket, name='tennis_bracket'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)